// ── UI stage ─────────────────────────────────────────────────
// The dropdown combines advancement (%) + status into one value.
// Converted to/from DB fields with helpers below.
export type UIStage = '0' | '15' | '30' | '50' | '75' | '100' | 'perdue';

export const AVANCEMENT_LABELS: Record<UIStage, string> = {
  '0':    '0% – Identifiée',
  '15':   '15% – Premier contact',
  '30':   '30% – Qualifiée',
  '50':   '50% – Proposition envoyée',
  '75':   '75% – Négociation',
  '100':  '100% – Gagnée',
  perdue: 'Perdue',
};

export function stageToFields(stage: UIStage): { advancement: number; status: OpportunityStatus } {
  if (stage === 'perdue') return { advancement: 0,   status: 'lost' };
  if (stage === '100')    return { advancement: 100, status: 'won'  };
  return { advancement: parseInt(stage, 10), status: 'active' };
}

export function fieldsToStage(advancement: number, status: OpportunityStatus): UIStage {
  if (status === 'lost') return 'perdue';
  return String(advancement) as UIStage;
}

// ── DB types ──────────────────────────────────────────────────
export type OpportunityStatus = 'active' | 'won' | 'lost';
export type ContactType = 'person' | 'company';

export interface Comment {
  date:   string;
  author: string;
  text:   string;
}

export interface Opportunity {
  id:                  string;
  numero:              string;
  company:             string;
  company_id?:         string;
  main_contact:        string;
  main_contact_id?:    string;
  other_contacts:      string;
  other_contact_ids?:  string[];
  estimated_amount:    number;
  advancement:         number;
  weighted_amount:     number;   // GENERATED by DB — never send on insert/update
  closing_date?:       string | null;
  mission_type:        string;
  status:              OpportunityStatus;
  description:         string;
  comments:            Comment[];
  created_at:          string;
  created_by:          string;
}

export interface Contact {
  id:                 string;
  type:               ContactType;
  first_name?:        string;
  last_name?:         string;
  position?:          string;
  phone?:             string;
  email?:             string;
  last_contact_date?: string;
  parent_company_id?: string;
  company_name?:      string;
  sector?:            string;
  revenue?:           number;
  address?:           string;
  relation_status?:   string;
  action_status?:     string;
  comments:           Comment[];
  created_at:         string;
  created_by:         string;
}

export interface Appointment {
  id:                     string;
  title:                  string;
  date:                   string;
  time:                   string;
  duration:               number;
  subject:                string;
  linked_contact_id?:     string;
  linked_opportunity_id?: string;
  notes:                  string;
  created_at:             string;
  created_by:             string;
}

export interface AppData {
  opportunities: Opportunity[];
  contacts:      Contact[];
  appointments:  Appointment[];
}

// Input types — exclude DB-managed fields from inserts/updates
export type OpportunityInsert = Omit<Opportunity, 'id' | 'numero' | 'weighted_amount' | 'created_at' | 'created_by'>;
export type ContactInsert     = Omit<Contact,      'id' | 'created_at' | 'created_by'>;
export type AppointmentInsert = Omit<Appointment,  'id' | 'created_at' | 'created_by'>;
